### ISSUE TITLE
Only works between October and March

### ISSUE THREAD

**Issue by NormanDunbar** [pfeerick/ISS-Notifier#1]
Hi Peter,

You are using Europe/London as your timezone to get UTC to match with the data returned from the ISS API call. 

Come March, we UK dwellers will revert to BST and your code here will be one hour out.

You need to extract the `raw_offset` field from the JSON and add it with a sign change, to `currentTime` to get back to UTC. Something like `currentTime += (-rawOffset)`.

Cheers,
Norm. :wink:

**Comment by pfeerick** [comment]
Well, the solution to that is to not live in a country/state that changes the clocks part of the year! :-P

All the code I wrote is perfect, **_perfect_** I tell you. I know I should have turned the issues tab off! 😆 

On a more serious note, thanks for spotting that... one of the next things on my agenda is to study the ISS API documentation and see how it worked, timezones, etc. I'm in the middle of adding support for a OLED display, so will add this in after that is done. Lookin at that now. I can see the timezone rule for `Europe/London` will apply a DST offset. So probably better to use the actual [`ETC/UTC`](http://worldtimeapi.org/timezone/Etc/UTC) timezone instead. Or I could pull the offset to show how it's possible to detect if DST is in effect.

**Comment by NormanDunbar** [comment]
I had a quick, very quick, look at the ISS API docs, and that's where I found the mention of all times being in UTC - which makes sense as there are so many timezones, they had to pick one. I didn't know that "etc/utc" was valid though on the World Time API - nice one, thanks.

Have fun.

Cheers,
Norm.

**Comment by pfeerick** [comment]
You had more of a look than I did/have then... I still haven't gotten there yet... I strongly suspected that it would be UTC, which is why I was surprised when I saw `Europe/London` used ... but thankfully when I checked World Time API it said it supported it, so why make my life any harder! 😉 😆
